AOSP_KeystoreFile=/home/jprodvx/Documents/Android App Keys/keyStore/rk3568_12.0.keystore
AOSP_KeystorePassword=android
AOSP_KeystoreAlias=androiddebugkey
AOSP_KeyPassword=android

EDLA_KeystoreFile=/home/jprodvx/Documents/Android App Keys/keyStore/a11_Prodvx.keystore
EDLA_KeystorePassword=android
EDLA_KeystoreAlias=androiddebugkey
EDLA_KeyPassword=android

EDLA13_KeystoreFile=/home/jprodvx/Documents/Android App Keys/keyStore/A13_Prodvx.keystore
EDLA13_KeystorePassword=android
EDLA13_KeystoreAlias=androiddebugkey
EDLA13_KeyPassword=android